openapi: 3.0.0
info:
  title: Splitup
  description: App to share expenses among friends
  contact:
    name: Dev Team
    url: https://github.com/manojnakp/splitup/issues
    email: manojna.gopher@gmail.com
  license:
    name: MIT license
    url: https://opensource.org/licenses/MIT
  version: 1.1.0
servers:
  - url: /
    description: default
tags:
  - name: splitcount
    x-displayName: Splitcounts
    description: CRUD Splitcounts
  - name: participant
    x-displayName: Participants
    description: Participants can be modified only if not involved in any expense
  - name: expense
    x-displayName: Expenses
    description: Expenses of a splitcount
  - name: other
    x-displayName: Others
    description: Balancing expenses among friends and other handy tools
paths:
  /all:
    $ref: paths/all.yaml
  /{id}:
    $ref: paths/{id}.yaml
  /new:
    $ref: paths/new.yaml
  /{id}/participants:
    $ref: paths/{id}_participants.yaml
  /{id}/participants/new:
    $ref: paths/{id}_participants_new.yaml
  /{id}/expenses/all:
    $ref: paths/{id}_expenses_all.yaml
  /{id}/expenses/new:
    $ref: paths/{id}_expenses_new.yaml
  /{id}/expenses/{eid}:
    $ref: paths/{id}_expenses_{eid}.yaml
  /{id}/balance:
    $ref: paths/{id}_balance.yaml
